### ISSUE TITLE
Not working with CF7 4.3.1 WP 4.4

### ISSUE THREAD

**Issue by ricardobrg** [magician11/wpcf7-email-verification#5]
Hello!

Just to let you know it's not working with CF7 4.3.1 + WP 4.4. The form is submitted and the email is sent without the sender verifying the email.

**Comment by darktemplate** [comment]
Hi Ricardo and magician11, have you guys found a way to make the plugin works with current version of wordpress and CF7 ? Or an alternative maybe ? 

Many thanks !

**Comment by darktemplate** [comment]
I'm not sure about this : 
==TODOs==

There are things to still be done..

    Allow verification to be set per form
    Custom from email and name fields per form

From where i can do that ? he plugin will works after that ?  Thanks !

**Comment by magician11** [comment]
Sorry guys. I haven't really looked at this plugin for a while. And am not planning on maintaining it.
